version: "3"

services:
    nginx:
        image: "nginx:alpine"
        restart: always
        links:
            - php-fpm
        volumes:
            - "./public:/wsc"
            - "./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "83:80"

    php-fpm:
        build: docker/php-fpm
        restart: always
        links:
            - mysql
        volumes:
            - "./public:/wsc"
            - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"

    mysql:
        image: "mysql:8"
        restart: always
        volumes:
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/files:/var/lib/mysql-files"
            - "./mysql/logs:/var/log/mysql"
            - "./mysql/conf:/etc/mysql"
            - "./mysql/conf/conf.d:/etc/mysql/conf.d"
        environment:
            MYSQL_ROOT_HOST: "172.*.*.*"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: "${MYSQL_DATABASE:-woltlab_suite}"
            MYSQL_USER: "${MYSQL_USER:-woltlab_suite}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD:-woltlab_suite}"
        ports:
            - "3306:3306"
        command:
          - mysqld
          - --innodb_buffer_pool_size=2G
          - --innodb_buffer_pool_instances=2

    redis:
        image: "redis:7-alpine"
        restart: always
        ports:
          - "6379:6379"
        command:
          - redis-server
          - --bind 0.0.0.0
